<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="base" params="wheel_radius wheel_joint_z_offset_from_base_link">

    <!-- Calculate vertical offset for base_footprint -->
    <xacro:property name="vertical_offset" value="${wheel_radius - wheel_joint_z_offset_from_base_link}"/>

    <!-- Base footprint -->
    <link name="base_footprint"/>

    <!-- Base link -->
    <link name="base_link">

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="10.0"/>
        <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
           <mesh filename="package://amiga_ros2_description/meshes/base_link.STL" scale="1 1 1"/>
        </geometry>
        <material name="dark_grey">
            <color rgba="0.2 0.2 0.2 1"/>
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
           <box size="1.0 0.6 0.2"/>
        </geometry>
      </collision>
      
    </link>

    <!-- Fixed joint from footprint to base_link -->
    <joint name="base_footprint_joint" type="fixed">
      <parent link="base_link"/>
      <child link="base_footprint"/>
      <origin xyz="0 0 -${vertical_offset}" rpy="0 0 0"/>
    </joint>

  </xacro:macro>

</robot>